import './globals.css';

export const metadata = {
  title: "PDF Editor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full ">
      <body className="h-full flex items-center justify-center bg-slate-200">
          {children}
      </body>
    </html>
  );
}