import CanvasProvider from '@/Context/CanvasContext';
import './globals.css';


export const metadata = {
  title: "PDF Editor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='w-screen h-screen m-0 p-0 '>
      <CanvasProvider>
      <body className="h-screen w-screen  flex justify-center items-center overflow-x-hidden">
          {children}
      </body>
      </CanvasProvider>
    </html>
  );
}